### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by schmiflo**
Added paper on using BERT for reward in unconditional text generation.

### CODE REVIEW

**Comment by tomohideshibata** [comment]
I have already added this paper to "Misc." section, thanks.

**Comment by schmiflo** [comment]
Generation would be more appropriate, I think.

**Comment by tomohideshibata** [comment]
Hmm, this model itself does not generate a text. 
If some additional related papers are published, I plan to add a new section like "Quality Estimator" including the following papers:
- Machine Translation Evaluation with BERT Regressor
- SumQE: a BERT-based Summary Quality Estimation Model

**Comment by schmiflo** [comment]
It does. Section 5 explains the experiments and the appendix has the generated sentences ;-)

**Comment by tomohideshibata** [comment]
I mean GRU is used for the generation, and BERT is just used for the reward calculator.
Anyway, I will rearrange the section organization. Thanks for your suggestion.

**Comment by schmiflo** [comment]
True! Maybe one day there will be a reward-specific section with BERTScore and MoverScore (you are missing this one [1])

[1] https://arxiv.org/abs/1909.02622

**Comment by tomohideshibata** [comment]
Thanks for letting me know the missing paper. I have added it, and made a "Quality evaluator" section. Thanks!

**Pull request closed without merging**
